// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiError = { error: string, message: string, };

/**
 * Pushed over SSE when the watcher sees the folder change on disk.
 */
export type ChangeEvent = { rootId: string, paths: Array<string>, 
/**
 * Set when this app made the change, so the client that made it can ignore the echo.
 */
origin: string | null, };

/**
 * How a document is rendered server-side and which viewer the client picks.
 */
export type DocumentKind = "markdown" | "docx" | "pdf" | "image" | "csv" | "text" | "binary";

export type DocumentMeta = { path: string, name: string, title: string, kind: DocumentKind, size: number, 
/**
 * Milliseconds since the epoch. Doubles as the optimistic-concurrency token:
 * a save must echo the value it read, or it is rejected as a conflict.
 */
mtimeMs: number, editable: boolean, tags?: Array<string>, };

export type DocumentPayload = { meta: DocumentMeta, 
/**
 * Rendered HTML. `None` for kinds the browser displays itself (image, pdf) or
 * cannot display at all (binary).
 */
html: string | null, frontmatter?: { [key in string]: string }, headings: Array<Heading>, backlinks: Array<LinkRef>, outlinks: Array<LinkRef>, 
/**
 * Set when a renderer degraded — the document still displays, but something was
 * skipped and the UI should say so rather than pretend the render was complete.
 */
renderWarning?: string | null, };

export type FolderEntry = { name: string, path: string, isDir: boolean, kind?: DocumentKind, size: number, mtimeMs: number, 
/**
 * Number of documents inside, for directories.
 */
childCount?: number, };

export type FolderListing = { path: string, name: string, 
/**
 * The folder's landing page, when an index file was found.
 */
index?: DocumentPayload, 
/**
 * Children, with the index file itself omitted so it is not listed below its own content.
 */
entries: Array<FolderEntry>, };

export type Heading = { depth: number, text: string, slug: string, };

/**
 * A reference from one document to another, used for both backlinks and outlinks.
 */
export type LinkRef = { path: string, title: string, 
/**
 * For a backlink, the line the link appears on, cut to a readable width around
 * it, so the reader learns why the other note links here without opening it.
 * An outlink carries none: the reader is already looking at that line.
 */
context: string | null, };

export type RenameRequest = { from: string, to: string, 
/**
 * Rewrite inbound links so the rename does not break references.
 */
updateLinks: boolean, };

export type RenameResult = { from: string, to: string, 
/**
 * Documents whose links were rewritten as part of the move.
 */
updated: Array<string>, };

export type RestoreRequest = { rootId: string, trashPath: string, };

export type RootInfo = { id: string, name: string, 
/**
 * True when wikilinks, backlinks, callouts and tags are active for this root.
 */
obsidianMode: boolean, readOnly: boolean, 
/**
 * Everything the index holds for this root, attachments included.
 */
documents: number, 
/**
 * The newest mtime in the root, so a landing page can say when it last changed.
 * `None` for a root with nothing in it.
 */
lastModifiedMs: number | null, };

/**
 * Returned with HTTP 409 when a save would overwrite a change made elsewhere —
 * typically Obsidian editing the same note. Both sides are included so the UI can
 * offer a real choice instead of silently losing one of them.
 */
export type SaveConflict = { path: string, yourContent: string, diskContent: string, diskMtimeMs: number, };

export type SaveRequest = { content: string, 
/**
 * The `mtimeMs` the client last read. A mismatch means someone else wrote the file.
 */
baseMtimeMs: number, };

export type SearchHit = { path: string, title: string, kind: DocumentKind, 
/**
 * Matched text with surrounding context; `**` marks the match for the UI to style.
 */
snippet: string, score: number, };

export type SessionInfo = { email: string, };

/**
 * Tick or untick one task-list checkbox.
 *
 * Deliberately not a content write: the request names a line and the state it wants, so
 * the narrowest possible edit is the only one this route can make.
 */
export type TaskToggleRequest = { 
/**
 * 1-based line in the markdown source, as rendered into `data-task-line`.
 */
line: number, checked: boolean, 
/**
 * The `mtimeMs` the client last read, exactly as a save carries it.
 */
baseMtimeMs: number, };

/**
 * One file sitting in a root's `.trash/`, ready to be put back.
 */
export type TrashEntry = { 
/**
 * Path inside `.trash/`, including any `(n)` suffix a repeat delete added.
 */
trashPath: string, 
/**
 * Where a restore puts it: the original layout with the collision suffix removed.
 */
originalPath: string, name: string, size: number, 
/**
 * A move keeps the file's mtime, so this is when the note was last edited — the
 * closest thing to a delete time the filesystem keeps.
 */
mtimeMs: number, };

export type TreeNode = { name: string, path: string, isDir: boolean, kind?: DocumentKind, children?: Array<TreeNode>, };
