// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiError = { error: string, message: string, };

/**
 * Pushed over SSE when the watcher sees the folder change on disk.
 */
export type ChangeEvent = { rootId: string, paths: Array<string>, 
/**
 * Set when this app made the change, so the client that made it can ignore the echo.
 */
origin: string | null, };

/**
 * How a document is rendered server-side and which viewer the client picks.
 */
export type DocumentKind = "markdown" | "docx" | "pdf" | "image" | "csv" | "text" | "binary";

export type DocumentMeta = { path: string, name: string, title: string, kind: DocumentKind, size: number, 
/**
 * Milliseconds since the epoch. Doubles as the optimistic-concurrency token:
 * a save must echo the value it read, or it is rejected as a conflict.
 */
mtimeMs: number, editable: boolean, tags?: Array<string>, };

export type DocumentPayload = { meta: DocumentMeta, 
/**
 * Rendered HTML. `None` for kinds the browser displays itself (image, pdf) or
 * cannot display at all (binary).
 */
html: string | null, frontmatter?: { [key in string]: string }, headings: Array<Heading>, backlinks: Array<LinkRef>, outlinks: Array<LinkRef>, 
/**
 * Set when a renderer degraded — the document still displays, but something was
 * skipped and the UI should say so rather than pretend the render was complete.
 */
renderWarning?: string | null, };

export type FolderEntry = { name: string, path: string, isDir: boolean, kind?: DocumentKind, size: number, mtimeMs: number, 
/**
 * Number of documents inside, for directories.
 */
childCount?: number, };

export type FolderListing = { path: string, name: string, 
/**
 * The folder's landing page, when an index file was found.
 */
index?: DocumentPayload, 
/**
 * Children, with the index file itself omitted so it is not listed below its own content.
 */
entries: Array<FolderEntry>, };

export type Heading = { depth: number, text: string, slug: string, };

/**
 * A reference from one document to another, used for both backlinks and outlinks.
 */
export type LinkRef = { path: string, title: string, };

export type RenameRequest = { from: string, to: string, 
/**
 * Rewrite inbound links so the rename does not break references.
 */
updateLinks: boolean, };

export type RenameResult = { from: string, to: string, 
/**
 * Documents whose links were rewritten as part of the move.
 */
updated: Array<string>, };

export type RootInfo = { id: string, name: string, 
/**
 * True when wikilinks, backlinks, callouts and tags are active for this root.
 */
obsidianMode: boolean, readOnly: boolean, };

/**
 * Returned with HTTP 409 when a save would overwrite a change made elsewhere —
 * typically Obsidian editing the same note. Both sides are included so the UI can
 * offer a real choice instead of silently losing one of them.
 */
export type SaveConflict = { path: string, yourContent: string, diskContent: string, diskMtimeMs: number, };

export type SaveRequest = { content: string, 
/**
 * The `mtimeMs` the client last read. A mismatch means someone else wrote the file.
 */
baseMtimeMs: number, };

export type SearchHit = { path: string, title: string, kind: DocumentKind, 
/**
 * Matched text with surrounding context; `**` marks the match for the UI to style.
 */
snippet: string, score: number, };

export type SessionInfo = { email: string, };

export type TreeNode = { name: string, path: string, isDir: boolean, kind?: DocumentKind, children?: Array<TreeNode>, };
