import { useEffect, useLayoutEffect, useRef, type MouseEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { hasMermaid, renderMermaid } from '../../lib/mermaid';
import { isExternalHref, resolveAssetUrl, resolveInternalRoute } from '../../lib/docLinks';
import { useTheme } from '../../state/theme-context';

/**
 * Called when a task-list checkbox is ticked. Returns whether the write succeeded, so the
 * checkbox can be put back if it did not.
 */
export type TaskToggleHandler = (line: number, checked: boolean) => Promise<boolean>;

interface HtmlContentProps {
  /**
   * Server-rendered HTML. It is generated by the backend from the user's own
   * files behind authentication, so it is inserted as markup by design; nothing
   * user-typed reaches this component through any other path.
   */
  html: string;
  rootId: string;
  /** The document this HTML came from, used to resolve relative links. */
  docPath: string;
  /** Omitted where the document is not editable; checkboxes then stay read-only. */
  onToggleTask?: TaskToggleHandler;
}

function taskBoxes(container: HTMLElement): NodeListOf<HTMLInputElement> {
  return container.querySelectorAll<HTMLInputElement>('input[data-task-line]');
}

/** The server tags each checkbox with its source line; this is what makes it clickable. */
function makeTasksInteractive(container: HTMLElement): void {
  for (const box of taskBoxes(container)) {
    box.disabled = false;
    box.setAttribute('aria-label', 'Toggle this task');
  }
}

/**
 * Where the document cannot be written — a read-only root, or a kind with no source —
 * put the checkboxes back to read-only rather than offering a control that cannot work.
 */
function makeTasksReadOnly(container: HTMLElement): void {
  for (const box of taskBoxes(container)) {
    box.disabled = true;
  }
}

/** Wide elements get their own scroll container so the page never scrolls sideways. */
function wrapWideElements(container: HTMLElement): void {
  const wide = container.querySelectorAll<HTMLElement>('table, .mermaid-source');
  for (const element of wide) {
    if (element.parentElement?.classList.contains('scroll-x')) continue;
    const wrapper = document.createElement('div');
    wrapper.className = 'scroll-x';
    element.replaceWith(wrapper);
    wrapper.append(element);
  }
}

function rewriteAssets(container: HTMLElement, rootId: string, docPath: string): void {
  for (const media of container.querySelectorAll<HTMLImageElement | HTMLSourceElement>('img[src], source[src]')) {
    const resolved = resolveAssetUrl(rootId, docPath, media.getAttribute('src') ?? '');
    if (resolved) media.setAttribute('src', resolved);
    if (media instanceof HTMLImageElement) media.loading = 'lazy';
  }
  for (const anchor of container.querySelectorAll<HTMLAnchorElement>('a[href]')) {
    if (isExternalHref(anchor.getAttribute('href') ?? '')) {
      anchor.target = '_blank';
      anchor.rel = 'noopener noreferrer';
    }
  }
}

export function HtmlContent({ html, rootId, docPath, onToggleTask }: HtmlContentProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();
  const { resolved: themeMode } = useTheme();

  // The container is React's; its contents are ours. Writing the markup here
  // rather than through dangerouslySetInnerHTML means a re-render can never
  // discard the post-processing below — or a rendered mermaid diagram — and a
  // remount re-runs this effect and rebuilds everything from scratch.
  useLayoutEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    container.innerHTML = html;
    wrapWideElements(container);
    rewriteAssets(container, rootId, docPath);
    if (onToggleTask) makeTasksInteractive(container);
    else makeTasksReadOnly(container);
  }, [html, rootId, docPath, onToggleTask]);

  // A native listener, not React's `onChange`: these checkboxes are injected as raw DOM,
  // and React's change event is built on a value tracker that only exists for inputs React
  // itself rendered, so it never fires for them. `change` also covers keyboard activation,
  // which `click` alone would miss.
  const toggleRef = useRef(onToggleTask);
  useEffect(() => {
    toggleRef.current = onToggleTask;
  }, [onToggleTask]);

  /** Checkboxes whose write has not come back yet, and the state each one asked for. */
  const inFlight = useRef(new WeakMap<HTMLInputElement, boolean>());
  const statusRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const onChange = (event: Event) => {
      const box = (event.target as HTMLElement | null)?.closest?.<HTMLInputElement>(
        'input[data-task-line]',
      );
      const toggle = toggleRef.current;
      if (!box || !toggle) return;

      // A second activation while the first is still in flight: hold the state the server
      // was already asked for rather than queueing a second write against a stale mtime.
      const alreadyWanted = inFlight.current.get(box);
      if (alreadyWanted !== undefined) {
        box.checked = alreadyWanted;
        return;
      }

      const line = Number(box.dataset.taskLine);
      if (!Number.isInteger(line)) return;

      // Show the tick straight away, then put it back if the write is refused. A checkbox
      // that waits for a round trip feels broken; one that lies about the file is worse.
      //
      // Deliberately not `box.disabled = true` for the round trip: a disabled element
      // cannot hold focus, so every toggle threw a keyboard user back to the top of the
      // document — on a checklist, once per item.
      const wanted = box.checked;
      inFlight.current.set(box, wanted);
      box.setAttribute('aria-busy', 'true');
      void toggle(line, wanted).then((saved) => {
        inFlight.current.delete(box);
        box.removeAttribute('aria-busy');
        if (saved) return;
        box.checked = !wanted;
        // The revert is otherwise silent, which for a screen-reader user is
        // indistinguishable from the write having worked.
        if (statusRef.current) {
          statusRef.current.textContent = 'That task could not be saved. The checkbox was put back.';
        }
      });
    };

    container.addEventListener('change', onChange);
    return () => container.removeEventListener('change', onChange);
  }, []);

  useEffect(() => {
    const container = containerRef.current;
    if (!container || !hasMermaid(container)) return;
    let cancelled = false;
    void renderMermaid(() => containerRef.current, themeMode, () => cancelled);
    return () => {
      cancelled = true;
    };
  }, [html, themeMode]);

  // Internal links stay in the SPA; anything external keeps normal behaviour.
  const onClick = (event: MouseEvent<HTMLDivElement>) => {
    if (event.defaultPrevented || event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey) return;
    const anchor = (event.target as HTMLElement).closest('a');
    if (!anchor || anchor.target === '_blank') return;
    const href = anchor.getAttribute('href') ?? '';
    const route = resolveInternalRoute(rootId, docPath, href);
    if (!route) return;
    event.preventDefault();
    void navigate(route);
  };

  return (
    <>
      <div className="prose" ref={containerRef} onClick={onClick} />
      <div ref={statusRef} className="sr-only" role="status" aria-live="polite" />
    </>
  );
}
