import { useEffect, useLayoutEffect, useRef, type MouseEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { hasMermaid, renderMermaid } from '../../lib/mermaid';
import { isExternalHref, resolveAssetUrl, resolveInternalRoute } from '../../lib/docLinks';
import { useTheme } from '../../state/theme-context';

interface HtmlContentProps {
  /**
   * Server-rendered HTML. It is generated by the backend from the user's own
   * files behind authentication, so it is inserted as markup by design; nothing
   * user-typed reaches this component through any other path.
   */
  html: string;
  rootId: string;
  /** The document this HTML came from, used to resolve relative links. */
  docPath: string;
}

/** Wide elements get their own scroll container so the page never scrolls sideways. */
function wrapWideElements(container: HTMLElement): void {
  const wide = container.querySelectorAll<HTMLElement>('table, .mermaid-source');
  for (const element of wide) {
    if (element.parentElement?.classList.contains('scroll-x')) continue;
    const wrapper = document.createElement('div');
    wrapper.className = 'scroll-x';
    element.replaceWith(wrapper);
    wrapper.append(element);
  }
}

function rewriteAssets(container: HTMLElement, rootId: string, docPath: string): void {
  for (const media of container.querySelectorAll<HTMLImageElement | HTMLSourceElement>('img[src], source[src]')) {
    const resolved = resolveAssetUrl(rootId, docPath, media.getAttribute('src') ?? '');
    if (resolved) media.setAttribute('src', resolved);
    if (media instanceof HTMLImageElement) media.loading = 'lazy';
  }
  for (const anchor of container.querySelectorAll<HTMLAnchorElement>('a[href]')) {
    if (isExternalHref(anchor.getAttribute('href') ?? '')) {
      anchor.target = '_blank';
      anchor.rel = 'noopener noreferrer';
    }
  }
}

export function HtmlContent({ html, rootId, docPath }: HtmlContentProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();
  const { resolved: themeMode } = useTheme();

  // The container is React's; its contents are ours. Writing the markup here
  // rather than through dangerouslySetInnerHTML means a re-render can never
  // discard the post-processing below — or a rendered mermaid diagram — and a
  // remount re-runs this effect and rebuilds everything from scratch.
  useLayoutEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    container.innerHTML = html;
    wrapWideElements(container);
    rewriteAssets(container, rootId, docPath);
  }, [html, rootId, docPath]);

  useEffect(() => {
    const container = containerRef.current;
    if (!container || !hasMermaid(container)) return;
    let cancelled = false;
    void renderMermaid(() => containerRef.current, themeMode, () => cancelled);
    return () => {
      cancelled = true;
    };
  }, [html, themeMode]);

  // Internal links stay in the SPA; anything external keeps normal behaviour.
  const onClick = (event: MouseEvent<HTMLDivElement>) => {
    if (event.defaultPrevented || event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey) return;
    const anchor = (event.target as HTMLElement).closest('a');
    if (!anchor || anchor.target === '_blank') return;
    const href = anchor.getAttribute('href') ?? '';
    const route = resolveInternalRoute(rootId, docPath, href);
    if (!route) return;
    event.preventDefault();
    void navigate(route);
  };

  return <div className="prose" ref={containerRef} onClick={onClick} />;
}
